# Generated by Django 2.1.5 on 2019-02-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_auto_20190204_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='completion',
        ),
    ]
