# Generated by Django 2.1.5 on 2019-02-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_remove_log_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='logParentDirID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logResourceID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logShareID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logShareUsersID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='logUserID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
