# Generated by Django 2.1.5 on 2019-02-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20190207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logContents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
