# Generated by Django 2.1.5 on 2019-02-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_auto_20190207_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('errorID', models.AutoField(primary_key=True, serialize=False)),
                ('errorQuery', models.TextField()),
                ('errorDateTime', models.DateTimeField()),
            ],
        ),
    ]
