# Generated by Django 2.1.5 on 2019-02-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLog',
            fields=[
                ('failedLogID', models.AutoField(primary_key=True, serialize=False)),
                ('failedLogContents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resourceID', models.AutoField(primary_key=True, serialize=False)),
                ('resourceName', models.CharField(max_length=50)),
                ('parentDirID', models.CharField(max_length=50)),
                ('fullPath', models.CharField(max_length=500)),
                ('fileSize', models.IntegerField()),
                ('fileType', models.CharField(choices=[('File', 'File'), ('Directory', 'Directory')], max_length=50)),
                ('childCount', models.IntegerField(default=0)),
                ('shareStatus', models.CharField(max_length=50)),
                ('revision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('shareID', models.AutoField(primary_key=True, serialize=False)),
                ('resourceID', models.CharField(max_length=50)),
                ('resourceName', models.CharField(max_length=50)),
                ('shareDateTime', models.DateTimeField()),
                ('revision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShareUsers',
            fields=[
                ('shareUsersKey', models.AutoField(primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, max_length=50, null=True)),
                ('revision', models.IntegerField(default=0)),
                ('shareID', models.ForeignKey(db_column='shareID', on_delete=django.db.models.deletion.CASCADE, to='drive.Shares')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shareusers',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='drive.Users'),
        ),
        migrations.AddField(
            model_name='resources',
            name='shareID',
            field=models.ForeignKey(blank=True, db_column='shareID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drive.Shares'),
        ),
        migrations.AddField(
            model_name='resources',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='drive.Users'),
        ),
    ]
