# Generated by Django 2.1.5 on 2019-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('logUUID', models.CharField(max_length=500)),
                ('logDateTime', models.DateTimeField()),
                ('logContents', models.TextField()),
            ],
        ),
    ]
