# Generated by Django 2.1.5 on 2019-02-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('errorID', models.AutoField(primary_key=True, serialize=False)),
                ('errorQuery', models.TextField()),
                ('errorDateTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='logUUID',
        ),
        migrations.AddField(
            model_name='log',
            name='logParentDirID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logResourceID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logShareID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logShareUsersID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='logType',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='logUserID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='logContents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
