# Generated by Django 2.1.5 on 2019-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20190124_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shares',
            name='revision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shareusers',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
