# Generated by Django 2.1.5 on 2019-01-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_failedlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedLog',
        ),
    ]
