# Generated by Django 2.1.5 on 2019-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_delete_failedlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLog',
            fields=[
                ('failedLogID', models.AutoField(primary_key=True, serialize=False)),
                ('failedLogContents', models.TextField()),
            ],
        ),
    ]
