# Generated by Django 2.1.5 on 2019-02-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_failedlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='shareusers',
            name='revision',
        ),
    ]
